### PR TITLE
Front page

### PR DESCRIPTION
**Pull request by Chilliwack**
I made changes to the index.md page in this branch to solve for issue #66. The latest blog now renders on the front page of the blog with a deep link to original post and reading time. The Post, Cal and About radio buttons are still on the bottom.

### CODE REVIEW

**Comment by k8hertweck** [comment]
It looks like you created this branch initially from the branch authorship-2, which already had changes related to the authorship issues. You have two options:

1. finish changes related to authorship using this PR (branch front-page), and we can merge everything at once 
2. cherry pick files and/or commits related to only front-page changes (or let me know what these changes are) and we can merge those now and wait on authorship

I think the first option would be easiest, but I'm happy to help either way. It would also help if you removed old branches that have already been merged or are otherwise superfluous (looks like this includes authorship, updated_blog_temp, updated_contrib.md, and maybe authorship-2)

**Comment by Chilliwack** [comment]
Dang it....I was trying to keep my commits and branches separate for each issue/overall tasks...

I'll choose 1 and port over the work I'm doing on authorship-2 branch into the front-page one on Monday then merge everything at once. This will take care of #64, #39, #66.

**Comment by k8hertweck** [comment]
No worries! I still do this (creating a branch from the wrong branch) every once in awhile. You should be able to merge authorship-2 into front-page without too much trouble (either locally or remotely), then delete the old branch and you should be good to go!

**Comment by Chilliwack** [comment]
Hey @k8hertweck - I think I'm good to go but would love for you to review before merging into master. I went ahead and merge 'authorship-2' into 'front_page' and resolved the conflicts but let me know if I missed something please. Thanks!

**Comment by k8hertweck** [comment]
This looks great! We can run by the rest of the team after we've finalized tags to see if there's anything that needs tweaking, but this is awesome, thanks!

**Pull request merged**
